const os = require('os');
// console.log(os.platform());
// console.log(os.homedir());
// console.log(os.type());
// console.log(os.uptime());
// console.log(os.totalmem());
// console.log(os.version());
// console.log(os.release());
// console.log(os.hostname());
// console.log(os.freemem());
// console.log(os.networkInterfaces());
// console.log(os.loadavg());
// console.log(os.cpus());
console.log(os.arch());